name = "dist-worker"
main = "src/worker.ts"
compatibility_date = "2023-08-07"

# Dev (default)
[vars]
ENVIRONMENT = 'dev'
DIRECTORY_LISTING = 'on'
CACHE_CONTROL = 'public, max-age=3600, s-maxage=14400'
DIRECTORY_CACHE_CONTROL = 'public, max-age=3600, s-maxage=14400'

[[r2_buckets]]
binding = "R2_BUCKET"
preview_bucket_name = "dist-dev"
bucket_name = "dist-dev"

# Staging
[env.staging]
[env.staging.vars]
workers_dev = true
ENVIRONMENT = 'staging'
DIRECTORY_LISTING = 'restricted'
CACHE_CONTROL = 'public, max-age=3600, s-maxage=14400'
DIRECTORY_CACHE_CONTROL = 'public, max-age=3600, s-maxage=14400'

[[env.staging.r2_buckets]]
binding = "R2_BUCKET"
preview_bucket_name = "dist-dev"
bucket_name = "dist-staging"

# Prod
[env.prod]
env.prod.routes = [
    { pattern = 'nodejs.org/dist/*', zone_name = 'nodejs.org' },
    { pattern = 'nodejs.org/download/*', zone_name = 'nodejs.org' },
    { pattern = 'nodejs.org/docs/*', zone_name = 'nodejs.org' },
    { pattern = 'nodejs.org/api/*', zone_name = 'nodejs.org' },
    { pattern = 'nodejs.org/metrics/*', zone_name = 'nodejs.org' },
]

[env.prod.vars]
ENVIRONMENT = 'prod'
DIRECTORY_LISTING = 'restricted'
CACHE_CONTROL = 'public, max-age=3600, s-maxage=14400'
DIRECTORY_CACHE_CONTROL = 'public, max-age=3600, s-maxage=14400'

[[env.prod.r2_buckets]]
binding = "R2_BUCKET"
preview_bucket_name = "dist-prod"
bucket_name = "dist-prod"
