name: Lint Checks (ESLint / Prettier)

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
      - labeled
    branches:
      - main

jobs:
  lint:
    name: Check Linting and Formatting
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' || github.event.action == 'ready_for_review' || github.event.action == 'synchronize' || (github.event.action == 'labeled' && github.event.label.name == 'force ci') }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Run ESLint
        run: npm run lint
