name: Promote Release

on:
  # Triggered by the dist server
  workflow_dispatch:
    inputs:
      path:
        description: 'path to promote'
        required: true
      recursive:
        description: 'is the path a directory'
        type: boolean
        required: true

jobs:
  promote-release:
    name: Promote Release
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Promote Files
        env:
          CF_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
          CF_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
        run: |
          node scripts/promote-release.mjs ${{ inputs.path }} ${{ inputs.recursive == true && '--recursive' || '' }}
